// scripts/lib/ratecard.mjs — shared logic for the pricing-page ↔ rate-card gate.
//
// The public pricing page (pricing/overview.mdx) is hand-written, but every price
// on it comes from Mnemom's rate card: a versioned YAML file in the private
// mnemom/mnemom-billing repo (ratecards/<version>.yaml). Two scripts use this
// module so they can never disagree about what a price means:
//
//   scripts/sync-ratecard.mjs          — fetches a rate-card YAML, reduces it to
//                                        the small public extract committed at
//                                        scripts/ratecard-snapshot.json, and (with
//                                        --check) fails if the committed extract has
//                                        drifted from mnemom-billing main.
//   scripts/check-pricing-ratecard.mjs — offline: fails if the pricing page's
//                                        prices differ from the committed extract.
//
// The extract deliberately keeps only customer-facing fields (peg, usage margin,
// and each class's rate model / unit / list rate). Provider cost tables, notes and
// internal commentary in the YAML are dropped: this docs repo is public.

import { parse as parseYaml } from "yaml";

export const RATECARD_REPO = "mnemom/mnemom-billing";

// Sentinels bounding the machine-checked region of the pricing page. Only table
// rows inside this region are parsed; prose elsewhere on the page is free text.
// In MDX the markers sit inside a JSX comment: {/* <!-- pricing-ratecard:start --> */}.
export const REGION_START = "<!-- pricing-ratecard:start -->";
export const REGION_END = "<!-- pricing-ratecard:end -->";

// Classes the page MUST list. These are the classes a customer can be charged for
// today, plus the non-LLM classes the page promises are free. Dropping one from
// the page is a failure, not a silent omission.
export const REQUIRED_PAGE_CLASSES = [
  "gateway.turn.governed",
  "gateway.sh.check",
  "gateway.context.fold",
  "kernel.observer.trace-analysis",
  "analyze.checkpoint",
  "analyze.zk-proof",
  "rg.run.person-card",
  "rg.run.company-card",
  "kernel.anchoring.base-l2",
  "kernel.egress.webhook",
  "kernel.egress.email",
];

// Wording from the retired pricing model that must not come back: Safe House
// "bundled" into the turn, flat per-request dollar prices, and plan subscriptions.
export const FORBIDDEN_PATTERNS = [
  { label: "'bundled' (Safe House and fold are billed as their own lines)", re: /\bbundled?\b/i },
  { label: "subscription wording (there are no plans to subscribe to)", re: /subscri(?:be|ption)/i },
  {
    label: "flat per-request dollar price",
    re: /\$\s?\d[\d.,]*\s*(?:per|\/|a|an|each)\s*(?:request|turn|call|check|screen|query)\b/i,
  },
];

const CLASS_ID_RE = /^[a-z0-9]+(?:\.[a-z0-9-]+)+$/;

function fail(msg) {
  throw new Error(msg);
}

/**
 * Reduce a rate-card YAML document to the committed public extract.
 * @param {string} yamlText
 * @param {{ path: string, ref: string }} source
 */
export function extractRatecard(yamlText, source) {
  const doc = parseYaml(yamlText);
  if (!doc || typeof doc !== "object") fail("rate card: not a YAML mapping");
  if (typeof doc.version !== "string" || !doc.version) fail("rate card: missing `version`");
  if (typeof doc.effectiveAt !== "string") fail(`rate card ${doc.version}: missing \`effectiveAt\``);
  const peg = doc.peg || {};
  if (typeof peg.mu_usd !== "number") fail(`rate card ${doc.version}: missing \`peg.mu_usd\``);
  if (!Array.isArray(doc.classes) || doc.classes.length === 0) fail(`rate card ${doc.version}: no \`classes\``);

  const margin = doc.usage_margin_pct ?? null;
  if (margin !== null && !(typeof margin === "number" && margin >= 0 && margin < 1)) {
    fail(`rate card ${doc.version}: usage_margin_pct must be a number in [0, 1), got ${margin}`);
  }

  const seen = new Set();
  const classes = doc.classes.map((c) => {
    if (!c || typeof c.class !== "string") fail(`rate card ${doc.version}: class entry without \`class\``);
    if (seen.has(c.class)) fail(`rate card ${doc.version}: duplicate class ${c.class}`);
    seen.add(c.class);
    if (typeof c.model !== "string") fail(`rate card ${doc.version}: ${c.class} has no \`model\``);
    const rate = c.rate_mu ?? null;
    if (c.model === "usage") {
      if (rate !== null) fail(`rate card ${doc.version}: usage class ${c.class} must not carry rate_mu`);
    } else if (typeof rate !== "number") {
      fail(`rate card ${doc.version}: ${c.model} class ${c.class} has no numeric rate_mu`);
    }
    return { class: c.class, model: c.model, unit: c.unit ?? null, rate_mu: rate };
  });
  classes.sort((a, b) => a.class.localeCompare(b.class));

  return {
    _note:
      "Public extract of a Mnemom rate card, generated by scripts/sync-ratecard.mjs. Do not hand-edit: " +
      "re-run the sync script. pricing/overview.mdx is checked against this file by " +
      "scripts/check-pricing-ratecard.mjs, and this file is checked against the rate card on the " +
      "billing repo's main branch by the scheduled 'Pricing rate card' workflow.",
    source: { repo: RATECARD_REPO, path: source.path, ref: source.ref },
    version: doc.version,
    effective_at: doc.effectiveAt,
    peg: { usd_per_mu: peg.mu_usd, mmu_per_mu: peg.mmu_per_mu ?? null },
    usage_margin_pct: margin,
    classes,
  };
}

export function serializeExtract(extract) {
  return JSON.stringify(extract, null, 2) + "\n";
}

/** Everything in an extract that affects a price, i.e. all but provenance. */
export function pricingFields(extract) {
  const { _note, source, ...rest } = extract;
  return rest;
}

/**
 * The charge multiplier on measured model cost implied by a gross-margin target:
 * charge = cost / (1 - margin). 0.80 → 5. Must come out a whole number, because
 * the page states it as "N×".
 */
export function usageMultiplier(margin) {
  if (margin === null || margin === undefined) {
    fail("rate card has no usage_margin_pct, so the page cannot state a usage multiplier");
  }
  const m = 1 / (1 - margin);
  const r = Math.round(m);
  if (Math.abs(m - r) > 1e-9) fail(`usage_margin_pct ${margin} gives a non-integer multiplier ${m}`);
  return r;
}

/** Parse the price cell of a pricing-page table row. */
export function parsePrice(cell) {
  const text = cell
    .replace(/\*\*|__|`/g, "")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .trim();
  if (/^free\b/i.test(text)) return { kind: "free" };
  const usage = text.match(/^(\d+)\s*[×x]\s+(?:the\s+)?measured model cost\b/i);
  if (usage) return { kind: "usage", multiplier: Number(usage[1]) };
  const fixed = text.match(/^(\d[\d,]*)\s*[μµ]/);
  if (fixed) return { kind: "fixed", mu: Number(fixed[1].replace(/,/g, "")) };
  return { kind: "unparseable", text };
}

function splitRow(line) {
  const t = line.trim();
  if (!t.startsWith("|")) return null;
  const cells = t.replace(/^\|/, "").replace(/\|$/, "").split("|").map((c) => c.trim());
  if (cells.every((c) => /^:?-{3,}:?$/.test(c))) return null; // separator row
  return cells;
}

/**
 * Extract the machine-checked region and its priced rows from the page.
 * @returns {{ region: string, rows: Array<{class: string, price: string, line: number}> }}
 */
export function parsePricingPage(mdx) {
  const starts = mdx.split(REGION_START).length - 1;
  const ends = mdx.split(REGION_END).length - 1;
  if (starts !== 1 || ends !== 1) {
    fail(`pricing page must contain exactly one ${REGION_START} … ${REGION_END} region (found ${starts} start, ${ends} end)`);
  }
  const startIdx = mdx.indexOf(REGION_START);
  const endIdx = mdx.indexOf(REGION_END);
  if (endIdx < startIdx) fail("pricing page region end marker comes before its start marker");
  const firstLine = mdx.slice(0, startIdx).split("\n").length;
  const region = mdx.slice(startIdx + REGION_START.length, endIdx);

  const rows = [];
  region.split("\n").forEach((line, i) => {
    const cells = splitRow(line);
    if (!cells) return;
    const ids = cells
      .map((c) => c.match(/^`([^`]+)`$/))
      .filter(Boolean)
      .map((m) => m[1])
      .filter((id) => CLASS_ID_RE.test(id));
    if (ids.length === 0) return; // header row or a row that names no class
    if (ids.length > 1) fail(`pricing page line ${firstLine + i}: a row names more than one class (${ids.join(", ")})`);
    rows.push({ class: ids[0], price: cells[cells.length - 1], line: firstLine + i });
  });
  return { region, rows };
}

/**
 * Compare the pricing page to a rate-card extract.
 * @returns {string[]} human-readable problems; empty means the page matches.
 */
export function checkPageAgainstExtract(mdx, extract) {
  const problems = [];
  let parsed;
  try {
    parsed = parsePricingPage(mdx);
  } catch (e) {
    return [e.message];
  }
  const { region, rows } = parsed;
  const byClass = new Map(extract.classes.map((c) => [c.class, c]));

  if (!region.includes("`" + extract.version + "`")) {
    problems.push(`the checked region must name the rate card version \`${extract.version}\``);
  }

  let multiplier = null;
  try {
    multiplier = usageMultiplier(extract.usage_margin_pct);
  } catch (e) {
    if (extract.classes.some((c) => c.model === "usage")) problems.push(e.message);
  }

  const onPage = new Set();
  for (const row of rows) {
    if (onPage.has(row.class)) {
      problems.push(`line ${row.line}: ${row.class} is listed more than once`);
      continue;
    }
    onPage.add(row.class);
    const cls = byClass.get(row.class);
    if (!cls) {
      problems.push(`line ${row.line}: ${row.class} is not a class on rate card ${extract.version}`);
      continue;
    }
    const price = parsePrice(row.price);
    if (price.kind === "unparseable") {
      problems.push(`line ${row.line}: cannot read the price "${price.text}" for ${row.class}`);
      continue;
    }
    if (cls.model === "usage") {
      if (price.kind !== "usage") {
        problems.push(`line ${row.line}: ${row.class} is usage-priced on the rate card; the page must say "${multiplier}× measured model cost"`);
      } else if (multiplier !== null && price.multiplier !== multiplier) {
        problems.push(`line ${row.line}: ${row.class} says ${price.multiplier}× but the rate card's margin implies ${multiplier}×`);
      }
    } else if (cls.rate_mu === 0) {
      if (price.kind !== "free") problems.push(`line ${row.line}: ${row.class} is free on the rate card; the page must say "Free"`);
    } else if (price.kind !== "fixed" || price.mu !== cls.rate_mu) {
      const shown = price.kind === "fixed" ? `${price.mu} μ` : price.kind;
      problems.push(`line ${row.line}: ${row.class} shows ${shown} but the rate card says ${cls.rate_mu} μ`);
    }
  }

  for (const req of REQUIRED_PAGE_CLASSES) {
    if (!onPage.has(req)) problems.push(`required class ${req} is missing from the checked region`);
  }

  // Page-wide facts stated in prose.
  const pegs = [...mdx.matchAll(/1\s*[μµ]\s*=\s*\$\s?([0-9.]+)/g)].map((m) => Number(m[1]));
  if (pegs.length === 0) problems.push(`the page must state the peg as "1 μ = $${extract.peg.usd_per_mu}"`);
  for (const p of pegs) {
    if (p !== extract.peg.usd_per_mu) problems.push(`the page states 1 μ = $${p}; the rate card peg is $${extract.peg.usd_per_mu}`);
  }
  if (extract.usage_margin_pct !== null) {
    const want = Math.round(extract.usage_margin_pct * 100);
    for (const m of mdx.matchAll(/(\d+)%\s+(?:gross\s+)?margin/gi)) {
      if (Number(m[1]) !== want) problems.push(`the page states a ${m[1]}% margin; the rate card margin is ${want}%`);
    }
    if (multiplier !== null) {
      for (const m of mdx.matchAll(/(\d+)\s*[×x]\s+(?:the\s+|its\s+)?measured\b/gi)) {
        if (Number(m[1]) !== multiplier) problems.push(`the page states ${m[1]}× measured cost; the rate card implies ${multiplier}×`);
      }
    }
  }

  const lines = mdx.split("\n");
  for (const { label, re } of FORBIDDEN_PATTERNS) {
    lines.forEach((line, i) => {
      if (re.test(line)) problems.push(`line ${i + 1}: retired pricing wording — ${label}`);
    });
  }

  return problems;
}

/**
 * Differences between two extracts, restricted to what the page shows: the peg,
 * the usage margin, and the listed classes. Used to tell whether a newer rate
 * card on the billing repo would change a price the page states.
 */
export function pageRelevantDiff(a, b, classes) {
  const diffs = [];
  if (a.peg.usd_per_mu !== b.peg.usd_per_mu) diffs.push(`peg ${a.peg.usd_per_mu} → ${b.peg.usd_per_mu}`);
  if (a.usage_margin_pct !== b.usage_margin_pct) diffs.push(`usage_margin_pct ${a.usage_margin_pct} → ${b.usage_margin_pct}`);
  const am = new Map(a.classes.map((c) => [c.class, c]));
  const bm = new Map(b.classes.map((c) => [c.class, c]));
  for (const id of classes) {
    const x = am.get(id);
    const y = bm.get(id);
    const fmt = (c) => (c ? `${c.model}${c.rate_mu === null ? "" : ` ${c.rate_mu} μ`}` : "absent");
    if (fmt(x) !== fmt(y)) diffs.push(`${id}: ${fmt(x)} → ${fmt(y)}`);
  }
  return diffs;
}
